#!/bin/sh
set -e
cd "$(dirname "$0")/.."

npm ci
go run cmd/build/main.go
if [ $(go env GOOS) = "windows" ]; then
    suffix=".exe"
else
    suffix=""
fi
go build -o build/minimalist-go-react-app-$(go env GOARCH)$suffix cmd/server/main.go
rm build/ui.js
