name: build
on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-latest-xlarge]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v1
        with:
          go-version: 1.22
      - uses: actions/setup-node@v4
        with:
          node-version: 22.2
      - run: ./scripts/build
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/minimalist-go-react-app

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            kajatools/minimalist-go-react-app:latest
