name: build
on:
  push:
    branches:
      "*"
  workflow_dispatch:
jobs:
  binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v1
        with:
          go-version: 1.22
      - uses: actions/setup-node@v4
        with:
          node-version: 22.2
      - run: ./scripts/build 
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            kajatools/minimalist-go-react-app:latest
