name: main
on:
  push:
    branches:
      - "main"
      - "wham/hello"
jobs:
  binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: ./scripts/build   
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            kajatools/minimalist-go-react-app:latest
